### ISSUE TITLE
High Priority: Unable to create nonce on additional domains

### ISSUE THREAD

**Issue by jabcreations** [square/connect-api-specification#93]
Due to what I'm guessing are server side headers being set for only the primary domain name on the account I am unable to have my customer's domains obtain a nonce. Load the following URL (all test/sandbox only) and fill in any card information that passes basic validation. When submitting the form it will spawn an error in the web developer console (I test with Gecko/Firefox/Waterfox).

https://www
fixedfirefox
com/admin/square.php

The error message in Firefox is:

Invalid postMessage origin: "https _ www _ fixedfirefox.com"

According to Tristan there is no domain name or other URL limitation for hosting the form. Clients will have absolutely zero access to the server, have zero access/control over anything sensitive and everything on all domains is SSL without exception. If this does not get fixed it will dump about two to four weeks of unforseen work for me. :-\

Here is the SO URL from yesterday:

https://stackoverflow.com/questions/47270464/add-domain-access-to-square-api?noredirect=1#comment81492740_47270464

**Comment by alecholmes** [comment]
Hi @jabcreations. The URL above does not work so I'm unable to check what is happening in that specific case.

"Invalid postMessage origin" can happen for a few reasons. A common one is the square.js Javascript library being served from a non-Square server. The error for invalid HTTPS is different ("SqPaymentForm can only be embedded on sites that use HTTPS.").

**Comment by jabcreations** [comment]
@alecholmes I have to load this page in an iframe due to a bug where your iframes won't load in the XML parser for Gecko/Firefox. Since I have to do that I then also have to have JavaScript detect the site theme and apply the applicable CSS property/values; once completed it removes the style attribute from the body where the opacity is set to 0. If you have cookies or JavaScript disabled you will need to enable them for the page to load. You can also manually remove the style attribute from the body element in your browser's web inspector.

After loading the same URL though from jabcreations.com I detected and then manually inserted the URL https://js.squareup.com/v2/f.js in to a script element as it was not loading on fixedfirefox.com however I am still receiving the same error in the web console.

**Comment by jabcreations** [comment]
@alecholmes Have you had the chance to access and verify? This bug is very critical and I haven't heard anything since the beginning of the week.

**Comment by brettstimmerman** [comment]
Hi @jabcreations, it looks like there is a compounding issue at play, but not for the reasons you suspect.

The root cause lies in the `Cannot read property 'toLowerCase' of null` error. This error is caused by passing `null` as an `inputStyles` value. It prevents the payment form from working correctly, and explains (in a very round about way) why a spurious cross-origin issue appeared.

The calls to `localStorage.getItem()` in your config can return `null` if the key doesn't exist in local storage, which can cause the payment form's style engine to throw. When the style engine throws, the payment form goes into a non-working state.

A quick fix on your end is to replace the calls to `localStorage.getItem` with static configs, or provide fallbacks in case of `null`. This should put the payment form back on track.

Meanwhile, we can do better about this type of style engine error and consider it a bug.

---

> I have to load this page in an iframe due to a bug where your iframes won't load in the XML parser for Gecko/Firefox.

Can you provide more detail here? A vast majority of our customers don't need to jump through such hoops. It could be that fixing the local storage issue may correct this.

> ... and then manually inserted the URL https://js.squareup.com/v2/f.js ...

This should not be necessary, and we **strongly** recommend not linking to this library directly.
Fixing the local storage issue may correct this as well.

**Comment by jabcreations** [comment]
@brettstimmerman I've been able to resolve the issue and everything is working well now even to the point where localhost testing works.

I reported the XML parser issue for Gecko/Firefox here: https://github.com/square/connect-api-specification/issues/86 though there has been no response. Until that issue is resolved I am forced to load the form in an iframe which I estimated added at least one to two weeks of extra work.

The f.js file is being requested numerous times; I'll post a separate report. **At my end the issue is resolved** though like you said _the error handling at Square's end could be more helpful_, that one burned at least a couple days of productivity.
